apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-poyz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-lotc-tenant/integ-app-yraf/hacbs-test-project-poyz@sha256:e2df3ae52f05f23f89d06a57617e14f2ae991d94178abdd1f13ee8ac47c40c15
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
